### ISSUE TITLE
Page title and description

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#105]

**Comment by mathaywarduk** [comment]
@IanHealey can you supply content for the description on this page? https://delicate-sfogliatella-4b6b83.netlify.app/components/preview/your-details.html

**Comment by IanHealey** [comment]
@mathaywarduk can I just confirm on this page in the portal will the personal details be pre-filled out in the fields so that the user can see what there details are that have already been submitted? If they are the text should be as below.

You can view and update your personal details below.

**Comment by mathaywarduk** [comment]
@IanHealey Yep that's right.
