### ISSUE TITLE
Multi-select drop-down

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#120]
Need a max-height on the unchecked checkboxes: 270px

**Comment by nternetinspired** [comment]
Addressed with https://github.com/madebykind/shu-event-form-styles/commit/e334cc04010ad782595498242ff95ca6bb72c914 and added additional subjects so it can be seen in action https://delicate-sfogliatella-4b6b83.netlify.app/components/detail/step3.html @mathaywarduk
