### ISSUE TITLE
Session clash message

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#126]
Check colours against design: https://xd.adobe.com/view/5321c5af-c741-4dd8-afa3-25582e87452f-0672/screen/b17cb18d-5a8e-4ee6-b695-5e17e5df275e/

**Comment by Ferguson536** [comment]
> These sessions are at the same time. Please remove one to continue

**Comment by nternetinspired** [comment]
Adressed by https://github.com/madebykind/shu-event-form-styles/commit/9f36b68251d0b3559e3ac3134878aca68d0f3a4b and https://github.com/madebykind/shu-event-form-styles/commit/909bd7501f62c94bde04a705b0aff5bf39659676
