### ISSUE TITLE
Itinerary confirmation - Session clash (same time/overlap)

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#128]
Check colours against design: https://xd.adobe.com/view/5321c5af-c741-4dd8-afa3-25582e87452f-0672/screen/f6958e1e-2c5a-4a4b-babd-78d4349256c3/

**Comment by nternetinspired** [comment]
Bug addressed with https://github.com/madebykind/shu-event-form-styles/commit/9f36b68251d0b3559e3ac3134878aca68d0f3a4b and https://github.com/madebykind/shu-event-form-styles/commit/909bd7501f62c94bde04a705b0aff5bf39659676
