### ISSUE TITLE
Sign in CTA

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#141]
Heading should be 36px and Meta Serif font

**Comment by mathaywarduk** [comment]
@IanHealey can you provide description content for this sign in CTA on this page: https://delicate-sfogliatella-4b6b83.netlify.app/components/preview/events.html (the big yellow box)

**Comment by IanHealey** [comment]
Sign in to your account if you want to view or amend your booking, or need to cancel your place.

**Comment by IanHealey** [comment]
Sign in to your account if you want to view or amend your bookings or need to cancel your place.
