### ISSUE TITLE
Itinerary introduction

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#146]

**Comment by mathaywarduk** [comment]
@IanHealey can you provide content for the introduction on this page (after Your plan for the day)
https://delicate-sfogliatella-4b6b83.netlify.app/components/preview/view-booking.html

**Comment by IanHealey** [comment]
@mathaywarduk for now use the text below but this may be tweaked slightly.

Check in at City Campus in the main entrance, or at Collegiate Campus in the Heart of the Campus. It takes about 20 minutes to travel between our campuses so please include travel time if you're planning to visit both.
