### ISSUE TITLE
Helper labels

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#155]
We currently do not have these - happy for you to go with what you think / industry standard

**Comment by mathaywarduk** [comment]
@IanHealey We've added helper labels to Email address and Postcode as examples. Can you let us know of any helper content for any of the fields you sent over on this issue: https://github.com/dx-shu/open-day-events-project/issues/156

**Comment by IanHealey** [comment]
@mathaywarduk we haven't really used any on other event forms. I am not sure we need them but I am happy for your guidance on this if you have any recommendations.
