### ISSUE TITLE
Optional labels

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#156]
@IanHealey Do we have a list of what is optional on the registration part of the event forms

@mathaywarduk 

Phone number
Address line 2
Post code (if United Kingdom not country of residence)
Special requirements

**Comment by IanHealey** [comment]
@mathaywarduk these are the optional fields

Phone number
Address line 2
Post code (if United Kingdom not country of residence)
Special requirements

**Comment by mathaywarduk** [comment]
@IanHealey Looks like we don't have address at all, can you send me all the fields so we can make sure the templates have everything in?

**Comment by IanHealey** [comment]
@mathaywarduk here are all the fields, let me know if you need more details about the field options they are in this spreadsheet 

https://docs.google.com/spreadsheets/d/1Mzj7o740d8iKARSVrp65Yv27xfhUQeVzgmPq4BfZ5o8/edit?usp=sharing

under the tab **Ian's test OD data for testing**

First name
Last name
Email
Date of birth
Phone number
Country of residence
Address line 1
Address line 2
City
Postcode
Nationality
Subject sessions (selected sessions)
Related subject sessions (selected sessions)
Support sessions  (selected sessions)
Drop in sessions  (selected sessions)
Study level
Study mode
Year of entry
Guests
Special requirements
Opt ins

**Comment by mathaywarduk** [comment]
Thanks @IanHealey

**Comment by nternetinspired** [comment]
Updated required / optional fields with https://github.com/madebykind/shu-event-form-styles/commit/6b86cd6e5bfea7679f69f24a867344f4b2752bc2
