### ISSUE TITLE
Section descriptions - all session screens

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#159]
- [x] Hardcoded content in issue

**Comment by Ferguson536** [comment]
```
**Subject sessions**
Choose the sessions that interest you
```

**Comment by Ferguson536** [comment]
> **Subject sessions**
Choose the sessions that interest you

>

**Comment by Ferguson536** [comment]
> **Related subject sessions**
> The session you have just selected has an optional additional session. Select a time you would like to attend

**Comment by Ferguson536** [comment]
> **Support sessions**
> Choose the support sessions that interest you

**Comment by Ferguson536** [comment]
> **Drop-in sessions**
> Please tick the boxes below if you are interested in any of the following sessions
