### ISSUE TITLE
Event list introduction

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#176]
@IanHealey Can you provide introductory text for this page please? https://delicate-sfogliatella-4b6b83.netlify.app/components/preview/events.html

**Comment by IanHealey** [comment]
@mathaywarduk this can be used for now but might be tweaked 

Want to see all that Sheffield Hallam University has to offer? Join us at an open day to find out about undergraduate and postgraduate courses, accommodation, support and more.
