### ISSUE TITLE
Bookings introduction

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#177]
@IanHealey Can you provide introductory text for this page please? https://delicate-sfogliatella-4b6b83.netlify.app/components/preview/your-bookings.html

**Comment by IanHealey** [comment]
@mathaywarduk 

The best way to get a feel for Sheffield Hallam is to come and visit. Manage the events you are attending below.

Want to come and look round? We run student-led tours of our campuses and accommodation every Wednesday. Book your place.
