### ISSUE TITLE
Duplicate in choose subject area checklist

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/events#187]
Duplicate subject areas being pulled through = IT is not duplicated so suspect data being pulled in

**Comment by mathaywarduk** [comment]
@Cyapow can you confirm the data you're receiving has duplications in it?

**Comment by mathaywarduk** [comment]
@Ferguson536 Supply a list of subjects and IDs and @Cyapow will hard-code these using a config file

**Comment by Cyapow** [comment]
@mathaywarduk Looks like this has already been fixed without them excel files provided
