### ISSUE TITLE
On my personal plan I can remove all sessions and still continue

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#198]
@Ferguson536 we need to think what to do if someone does this. Disable the continue button and show a message saying something like: "You have no sessions in your itinerary, go back and select some" - link back to first session selection page

**Comment by mathaywarduk** [comment]
@Cyapow User has to have at least one session booked, so show a message and a link to 'go back' to session selection.

e.g.

"You have no sessions in your itinerary, go back and select some"

**Comment by Cyapow** [comment]
I've made it so you can't progress from step 4 without selecting at least one session. Same as step 5

**Comment by mathaywarduk** [comment]
@Cyapow it's on Step 6 really. I can remove all the sessions and then click "Confirm Itinerary"

**Comment by mathaywarduk** [comment]
I can also remove all sessions when viewing an existing booking. Should I be able to do this @Ferguson536 @IanHealey ?
