### ISSUE TITLE
Sessions not showing / crossover content from other forms 

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#199]
I've already been through the Ian's Open Day booking flow (although obviously can't submit that yet).

If I go to another flow that I haven't started before, e.g. "PG open virtual Ians", the subjects of interest are pre-selected (which might be ok @Ferguson536?) and no sessions are shown.

**Comment by Cyapow** [comment]
@mathaywarduk @Ferguson536 if the user goes to book another event should it reset all but the first form?

Also the other events have no sessions. Thats why you can't progress

**Comment by mathaywarduk** [comment]
@Cyapow Yeah I'd say so

**Comment by Ferguson536** [comment]
@IanHealey
