### ISSUE TITLE
Strange character on checkbox

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#201]
Might just be my machine, but was fine yesterday
<img width="642" alt="Screenshot 2022-06-30 at 14 34 53" src="https://user-images.githubusercontent.com/795907/176690849-4b3d5636-2de5-476a-8ce8-e31df13e2799.png">
y

**Comment by Cyapow** [comment]
@mathaywarduk if you inspect the element can you see anything there? Does look odd

**Comment by mathaywarduk** [comment]
@Cyapow don't think this is an issue anymore. Must've been a weird day!
