### ISSUE TITLE
Drop-in sessions

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#222]
We have a bit of an issue with the drop-in sessions (last group of sessions).

Because they're open all day for students to drop in whenever, they are set in Dynamics as lasting 6 hours from 9:30am.

This means, if selected, they will clash with every other session chosen.

So we need to change the logic for **this group only**.

On step 5 (https://matchapman.dev/book/5/f6b1cbeb-2bc6-ec11-a7b6-000d3a4b1e97)

- [x] Ignore all clashes or campus changes with drop-in sessions
- [x] Remove the duration (360 mins) for all drop-in sessions
- [x] Change the time (9:30) to "Anytime" for all drop-in sessions

On step 6 (https://matchapman.dev/book/6/f6b1cbeb-2bc6-ec11-a7b6-000d3a4b1e97)

- [x] Ignore all clashes or campus changes with drop-in sessions
- [x] Put all drop-in sessions at bottom of itinerary, regardless of the time
- [x] Remove the duration (6 hours) for all drop-in sessions
- [x] Change the time (9:30) to "Anytime" for all drop-in sessions

**Comment by Cyapow** [comment]
@mathaywarduk done

**Comment by mathaywarduk** [comment]
@Cyapow unchecked two above that still need doing
