### ISSUE TITLE
Long words in title cause horizontal scrolling

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#247]
Change to 48px on mobile?

![IMG_7059](https://user-images.githubusercontent.com/795907/179722395-074d4cf5-74bd-4ec8-b38f-88554c982dc3.PNG)

**Comment by nternetinspired** [comment]
Still didn't fit at 48px on iPhone 12/13 so I dropped h1 to 36px on mobes @mathaywarduk
