### ISSUE TITLE
PDF - Room information not showing

### ISSUE THREAD

**Issue by mathaywarduk** [dx-shu/events#252]
This wasn't showing on test either, so is likely a code issue.

Building is showing, but not the room that the session is in.

**Comment by Cyapow** [comment]
@Ferguson536 @mathaywarduk have you double checked the sessions actually have a room attached. Not many sessions on the matchapman.dev actually had a room attached to them

**Comment by Ferguson536** [comment]
@mathaywarduk When they copied the event in test they rooms were not copied over. So you cant see in test.

They work the same way as buildings do
If an event has Sessions (Open Day), then the Building and Room field for each session sits in the msevtmgt_Session table. These are msevtmgt_building and msevtmgt_room. These are Lookup fields to the tables of the same names.

We have added
to the 
Test server
Undergraduate Open Day
Accommodation 1145 session
Building Stoddard
Room Stoddard 1

Accounting, Banking and Finance subject talk
1045
Building - Charles st
Room - Boardroom 1

**Comment by Ferguson536** [comment]
Acceptance Criteria - Pulls through room onto the PDF (nowhere else)

**Comment by Ferguson536** [comment]
UPDATE - THIS WORKS IN TEST - Ian has just seen it on the PDF

**Comment by Ferguson536** [comment]
UPDATE - THIS WORKS IN LIVE - TICKET MARKED AS DONE
