### ISSUE TITLE
Open evening event not submitting

### ISSUE THREAD

**Issue by KidRollo** [dx-shu/events#258]
The following event form is not submitting data to Dynamics:
https://events.shu.ac.uk/book/1/f1ae5373-618e-4042-b2fc-793e5bc438af/open-evening

On submission the user gets the following error:
There was a problem booking your event.
Message: The data given was invalid.

Seems to happen no matter what is selected and submitted.

**Comment by Cyapow** [comment]
We had a bunch of event type IDs set in the config/shu.php to validate event types. 

The selected event didn't match those types so would fail on submission. I have removed the validation for it. However we still send it up so we can determine weather to check for subjects or courses

**Comment by KidRollo** [comment]
@Cyapow thanks for the quick fix on this one. Am I right in thinking that config/shu.php should ideally contain a valid event type ID in future for this type of event? If so I will pass that back to the Dynamics team.

**Comment by Cyapow** [comment]
@KidRollo it won't check now so shouldn't be an issue. It only uses the list in that to determine on the front end if we have to do certain things like skip a page or show fields etc

**Comment by KidRollo** [comment]
Great stuff. I've informed our colleagues in MCAT that there is an update ready to be pushed. 
Will close this ticket once that has been done and tested.

**Comment by KidRollo** [comment]
@Cyapow just had an update. The event ID for this form should have been: 993430012
But if we don't need it then I'm happy to leave it out.

**Comment by KidRollo** [comment]
Testers have confirmed this is working on our test environment https://events-test.shu.ac.uk/ 
Now moving to live
